- name: Creating the DB layer
  hosts: DB
  become: yes
  #tags:
   # - DB
  tasks:
    - name: Installing the mariadb server
      yum: 
        name: "{{item}}"
        state: latest
      loop:
        - mariadb
        - mariadb-server
    #    - MySQL-python
    - name: starting the DB server
      service: 
        name: mariadb
        state: stopped
